import { IsString, IsUUID, MinLength } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class SubmitCommandDto {
  @ApiProperty({ description: 'The shell command line to execute.' })
  @IsString()
  @MinLength(1)
  command!: string;

  @ApiProperty({
    description: 'UUID generated by the client per submission. Enforces idempotency.',
  })
  @IsUUID()
  clientCommandId!: string;
}
